### PR TITLE
remove get_val from script-fun

### PR DESCRIPTION
**Pull request by mekolat**
The plan is to remove get_val and get_val2 completely
... still fiddling with getarraysize

### CODE REVIEW

**Comment by mekolat** [comment]
@wushin I can't solve that travis error :cry:

**Comment by mekolat** [comment]
@wushin it's finally building :D

**Comment by mekolat** [comment]
@wushin remove the bug label
script debug : 0 110000012 : Dye Fail: CottonShirt
^ there's a problem with getarraysize

**Comment by wushin** [comment]
countitem doesn't work

**Comment by mekolat** [comment]
I'll look into it

**Pull request closed without merging**
