### PR TITLE
Update Travis for gcc 5

### PR DESCRIPTION
**Pull request by wushin**

### CODE REVIEW

**Comment by mekolat** [comment]
Same error over and over: `error: body of constexpr function (...) not a return-statement`

**Comment by mekolat** [comment]
can we remove gcc 4.7? (both of them)

**Comment by mekolat** [comment]
also, https://github.com/themanaworld/tmwa/blob/master/README.md#c-compiler

**Comment by mekolat** [comment]
```
error: the mangled name of ‘constexpr _Tp&& std::forward(typename std::remove_reference<_From>::type&) [with _Tp = std::nullptr_t; typename std::remove_reference<_From>::type = std::nullptr_t]’ changes between -fabi-version=6 (_ZSt7forwardIDnEOT_RNSt16remove_referenceIS1_E4typeE) and -fabi-version=0 (_ZSt7forwardIDnEOT_RNSt16remove_referenceIS0_E4typeE) [-Werror=abi]
```

**Comment by wushin** [comment]
4.7 is most likely still used in distros

**Comment by nashley** [comment]
I think most use 4.8, or (in the case of arch) 4.9
I don't think that gcc 5 is being used by any distros on their stable releases/branches yet.
What exactly is causing these versions of gcc to fail?

**Comment by wushin** [comment]
@nashley Not sure, but I figured we ought to poke are head into it as it will be going on the next Testing release for deb & ubuntu it looks.

**Comment by wushin** [comment]
:Happy: :dancer:

**Comment by mekolat** [comment]
yay! now let's remove 4.7

**Pull request merged**
