### PR TITLE
Stop sending 0x007b for mob movement

### PR DESCRIPTION
**Pull request by Rawng**
Rely solely on 0x0225 (move3)

### CODE REVIEW

**Comment by Rawng** [comment]
this should fix the recent issues with mob position

**Comment by mekolat** [comment]
@Rawng not at all. ManaPlus just [ignores](https://github.com/ManaPlus/ManaPlus/blob/master/src/net/tmwa/beinghandler.cpp#L1223) 0x007b if there is move3 [which is hardcoded](https://github.com/ManaPlus/ManaPlus/blob/master/src/net/tmwa/serverfeatures.cpp#L102) so we just can't disable it while we find the bug

**Comment by mekolat** [comment]
And don't just remove 7b. it's required for old clients so if you really musn't send it then add a version check

**Comment by mekolat** [comment]
hm oddly enough not sending 0x7b seems to fix it (must be because `dstBeing->setTileCoords(srcX, srcY)` is still set) so I'll just integrate this fix in my old mob move branch

**Comment by mekolat** [comment]
moved to https://github.com/themanaworld/tmwa/pull/130

**Comment by Rawng** [comment]
manaplus does not ignore 007b if move 3 is present. what it actually does is use the dest coords in 007b if move 3 is available. this is obviously incorrect behavior.

if you want to add a version check feel free to. supporting old clients isn't something I think is worth while.

I'm not sure exactly why deprecating 007b works, but I think it is some kind of packet ordering and handling bug in manaplus. in its current state it certainly doesn't handle both 007b and 0225 correctly.

**Comment by Rawng** [comment]
I guess I was wrong about what manaplus does with dest coords in 007b if 0225 is available, it looks like it tried to do the right thing.

either way it doesn't handle receiving both correctly.

**Pull request closed without merging**
