### PR TITLE
Bringing native guilds back to tmwa <alpha>

### PR DESCRIPTION
**Pull request by Rawng**
What should work:

```
  Creating a guild with /createguild <name>
  Inviting others with    /guild <name> or /invite <name> or the invite button with guild tab selected
  Leaving a guild with the leave button with guild tab selected
  Guild deletion via all members leaving the guild.
  Guild persistence between logins and server reboots (barring a crash before db save)
```

### CODE REVIEW

**Comment by Rawng** [comment]
@wushin @mekolat @nashley 

This is not ready for release as required features are still missing and implemented features are somewhat buggy.

This is primarily intended to solicit feedback, help find bugs, get some merge conflicts early and fix any travis build issues.

**Comment by wushin** [comment]
@Rawng I put this on test, but got an error
mapif_parse_GuildInfo : Fatal Error!

Is it missing confs?

**Comment by Rawng** [comment]
https://github.com/Rawng/ManaPlus/tree/guild

You can use this branch of Manaplus to test the new guild features.

The only change needed is to edit line 79 in src/net/tmwa/serverfeatures.cpp to 'return true;'

**Comment by wushin** [comment]
Nice tested and most things worked. Sometimes you had to log out and back in again for them to take effect. But gj so far. I wish someone else would have been online so I could have tested more.

**Comment by wushin** [comment]
Its always that map clif that seems to be the merge conflict. looks good so far though

**Comment by Rawng** [comment]
Guild chat now works

**Comment by wushin** [comment]
:D

**Comment by Rawng** [comment]
Things fixed:
* Guild social tab should reflect members logging out
* Players in a guild can no longer receive further invites
* Guild social tab should reflect newly added members
* Players in a guild can no longer create new guilds
* Requested guild name checked in various ways for validity

Things learned: 
* Manaplus does not display the inviting players name to the invitee
    * "has invited you to join the guild <guildname>" cannot send inviting player's name.
* Manaplus does not announce new members names in the guild chat tab.
    * "User has joined your guild" -- cannot send user name.

**Comment by Rawng** [comment]
Added preliminary script builtin "createguild" takes 1 argument, a string of 24 characters.

**Comment by wushin** [comment]
Will the code restrict people from using the /createguild in M+

**Comment by Rawng** [comment]
Not yet, but this is planned once creating via npc is known to work right

**Comment by wushin** [comment]
Taking this off test while https://forums.themanaworld.org/viewtopic.php?f=2&t=19064 takes place.

**Comment by wushin** [comment]
@Rawng we changed something in the core code and now I can't get guild to build.

**Comment by Rawng** [comment]
@wushin i don't currently have access to a Linux machine to do any development unfortunately. getting Linux on my new laptop is at the top of my priority list though so hopefully I will be able to return soon.

**Comment by Rawng** [comment]
also if you could post the commit that broke it it will make it easier to fix

**Comment by wushin** [comment]
@mekolat is investigating as we speak.

**Comment by Rawng** [comment]
Committed wushin's updates regarding MIN_CLIENT_VERSION, should be up to date for now.

**Comment by wushin** [comment]
:D

**Comment by wushin** [comment]
@Rawng did you see the new changes @4144 added to M+ for guild badges?

**Comment by Rawng** [comment]
It looks like there's no way for us to support this for now.

**Comment by Rawng** [comment]
Added: ability to expel/kick a guild member
Added: script builtin for leaving guild
Fixed: an online/offline state issue

**Comment by wushin** [comment]
@Rawng is this still stable enough for test?

**Comment by Rawng** [comment]
added packets:
	smsg_guild_pos_name_list <0x0166>
	smsg_guild_member_pos_change <0x0156>
	cmsg_guild_change_member_pos <0x0155>
	guild position change notify <0x3039>
	guild position change forward <0x3839>
changed 'leader' flag to 'position'
	1 - Guild Master
		Invite Member
		Kick Member
		Change Position
		Break Guild
	2 - Executor
		Invite Member
		Kick Member
		Change Position
	3 - Officer
		Invite Member
	4 - Member
changed default position value from 0 to 4 (member)
added ability for guild position 2 to kick members
don't allow guild leader to be kicked
limited inviting players to positions 1, 2, and 3
added position change action for positions 1 and 2
send guild position change to all map servers
reduced MAX_GUILD from 120 to 60

**Comment by Rawng** [comment]
notes:
- GM commands added
  - @createguild guild name,guild leader
  - @breakguild guild name
  - @listguildmembers guild name
  - @chngeguildmemberposition guild name,member,position
  - @addtoguild guild name,name
  - @removefromguild guild name,name

@commands with multiple arguments use comma separators, with no spaces between
  - for,example,like,this

**Comment by mekolat** [comment]
@Rawng this will be problematic because char names can have commas in them. Maybe we could use `/` or `|` ?

**Comment by Rawng** [comment]
@mekolat I want aware of that,  thanks.  Will update someone soon

**Comment by wushin** [comment]
@Rawng By any chance while doing this have you stumbled on the private chat channels M+ does ? Ping me in IRC so I know where you are at, we've not forgotten about this PR

**Comment by wushin** [comment]
@Rawng any chance you could work with @pydsigner at LoF at testing & finishing this off to get it merged? LoF is on master TMWA now. They did ask about native guilds. I could help out a bit once I get my gendered chars PR on TMWA test.

**Pull request closed without merging**
