### PR TITLE
Fix @pvp broken nick problem

### PR DESCRIPTION
**Pull request by wushin**

### CODE REVIEW

**Comment by mekolat** [comment]
how is that a broken nick? it's too short?

**Comment by wushin** [comment]
Doesn't like the PvP : preface, but Server : Whatever is fine

**Comment by mekolat** [comment]
might be the length then

**Comment by wushin** [comment]
Its literally anything but Server :

**Comment by mekolat** [comment]
https://github.com/ManaPlus/ManaPlus/blob/master/src/gui/windows/chatwindow.cpp#L1561

**Comment by wushin** [comment]
Well not sure how-to make PvP more than 3 char

**Comment by mekolat** [comment]
yes `Server` is fine.. but I have no clue why 4144 put a minimum length

**Pull request merged**
