### PR TITLE
Allow Email to be sent when registering

### PR DESCRIPTION
**Pull request by wushin**

### CODE REVIEW

**Comment by mekolat** [comment]
perhaps we should ask @o11c why it was removed

**Comment by wushin** [comment]
@mekolat I think @o11c got it to this point were it could be fixed as it's not worked forever.

**Comment by o11c** [comment]
The whole point of "fixed packet"s is that it is impossible to change their size. That's the reason that my plan was for *all* new packets to be variable-sized, even if their *current* needs only need a fixed-size one (it also simplifies the control loop).

You have to introduce a new packet, then add logic in the client to use it when the TMW server version is high enough.

**Comment by mekolat** [comment]
@o11c thanks, that's easy enough to do now that we have protocol.py :+1:

---
@wushin while creating a new packet we should also add captcha to it (captcha provider, version, key, validation)

**Comment by mekolat** [comment]
adding undesirable on this PR because we won't do it this way

**Comment by wushin** [comment]
@mekolat agree. we should make registration work like web with captcha and such.

**Pull request closed without merging**
