### PR TITLE
FreeBSD support

### PR DESCRIPTION
**Pull request by monwarez**
I have made some changes to get it build on FreeBSD platform.

### CODE REVIEW

**Comment by mekolat** [comment]
I guess I'll need to set up a freebsd VM to test as travis doesn't have bsd builds

**Comment by monwarez** [comment]
Actually this changes are not enough to build directly with ./configure --user and gmake
after ./configure --user , we have to change the some line in the Makefile
Like for example: $(shell make -f ${SRC_DIR}/generate.make >&2) have to be changed in
$(shell gmake -f ${SRC_DIR}/generate.make >&2)
And don't forget to only use gmake
The other issue is the command install who does not have the same order (for the install_data ) : ${install_data} src destdir 
And finally, ln do not have the option T

**Comment by monwarez** [comment]
the -S option on env is not standard but works on FreeBSD

**Comment by monwarez** [comment]
I have an idea, we should do a script that replace in every files in tools/ , the line #!/bin/bash arg by
#!/usr/bin/env -S bash arg , if uname -o equal FreeBSD when doing make, and an other script for make clean who reverse the previous script

**Comment by mekolat** [comment]
@monwarez if you want to investigate: https://github.com/themanaworld/tmwa/blob/master/src/map/magic-expr.cpp#L384
https://github.com/themanaworld/tmwa/blob/master/src/map/magic-v2.cpp#L1289

**Comment by monwarez** [comment]
I check the log, they have problem during test stage: make -R -k -j2 test

**Comment by monwarez** [comment]
I don't understand why travis don't work, it's build on linux, not FreeBSD so except if it does not like tab at beginning of a line my change should not get compiled
Except if master does not pass travis

**Comment by mekolat** [comment]
master of course passes travis

**Comment by monwarez** [comment]
I do some research, for the moment, I found that TOK_TOKEN are returned by Lexer::_adv()
when parsing information between ( and ), so the TOK_TOKEN error is for:"String is not entirely printable" line 176 in stable branch.
Maybe it's encoding problem with the magic files

**Pull request closed without merging**
