### PR TITLE
Send mob max_hp and hp to client in packet 0x007b

### PR DESCRIPTION
**Pull request by Rawng**

### CODE REVIEW

**Comment by wushin** [comment]
@Rawng this is merged on TMWA test. Please test

**Comment by mekolat** [comment]
@wushin I don't see any visible difference o_o

**Comment by Rawng** [comment]
@mekolat did you modify manaplus to not ignore the new values from tmwa?

**Comment by wushin** [comment]
@Rawng I changed the line to allow those 2 bits of the packets but whats the difference we are supposed to see here?

**Pull request merged**
